### ISSUE TITLE
Create a contact info block

### ISSUE THREAD

**Issue by tbezrukava** [tbezrukava/homepage#2]
Add links to social networks (LinkedIn, Facebook, Instagram), phone number, email, Telegram username, etc.

**Comment by tebex91** [comment]
location - Novomoskovsk, Ukraine
facebook - https://www.facebook.com/tetiana.bezrukava
telegram - @tbezrukava 
email - tetiana.bezrukava@gmail.com

**Comment by tbezrukava** [comment]
> location - Novomoskovsk, Ukraine facebook - https://www.facebook.com/tetiana.bezrukava telegram - @tbezrukava email - [tetiana.bezrukava@gmail.com](mailto:tetiana.bezrukava@gmail.com)

change facebook to age - 30
