### ISSUE TITLE
Create a timeline

### ISSUE THREAD

**Issue by tbezrukava** [tbezrukava/homepage#3]
Add a list of all your activities, achievements, work experience. Add as much info as you can remember. In case you don't have working experience tell about your pet-projects or student projects.

**Comment by tebex91** [comment]
**2018 - 2020**
EOS DATA ANALYTICS
HR manager
- newcomers adaptation, 1 to 1, review
- hr administration
- event organization

**2016 - 2017**
Publishing House "Pero"
Sales manager

**2014 - 2015**
LTD Mitra
Sales manager

**Comment by tbezrukava** [comment]
Good
